// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greetpb/greetpb.proto

package greetpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Greeting struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a70e130d9a778f5, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Greeting) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a70e130d9a778f5, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Errors               []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a70e130d9a778f5, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *GreetResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a70e130d9a778f5, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
	proto.RegisterType((*Error)(nil), "greet.Error")
}

func init() { proto.RegisterFile("proto/greetpb/greetpb.proto", fileDescriptor_0a70e130d9a778f5) }

var fileDescriptor_0a70e130d9a778f5 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x40,
	0x0c, 0x85, 0x69, 0x21, 0x25, 0x71, 0x8a, 0x90, 0x0c, 0x43, 0x55, 0x18, 0xa2, 0x13, 0x43, 0x25,
	0xa4, 0x20, 0x05, 0x36, 0xc4, 0x82, 0x8a, 0x98, 0x39, 0x36, 0xb6, 0x36, 0x35, 0xd1, 0x49, 0x90,
	0x0b, 0xbe, 0x83, 0xdf, 0x8f, 0xea, 0xba, 0x21, 0x4c, 0xf1, 0xfb, 0x9c, 0x7b, 0xf6, 0x33, 0x5c,
	0x74, 0xec, 0xa3, 0xbf, 0x69, 0x98, 0x28, 0x76, 0xeb, 0xfd, 0xb7, 0x14, 0x8a, 0x89, 0x48, 0xb3,
	0x84, 0xf4, 0x79, 0x5b, 0xb8, 0xb6, 0xc1, 0x4b, 0xc8, 0xde, 0x1d, 0x87, 0xd8, 0xae, 0x3e, 0x69,
	0x36, 0x2a, 0x46, 0x8b, 0xcc, 0xfe, 0x01, 0x9c, 0x43, 0xfa, 0xb1, 0xd2, 0xe6, 0x58, 0x9a, 0xbd,
	0x36, 0xf7, 0x30, 0x15, 0x17, 0x4b, 0x5f, 0xdf, 0x14, 0x22, 0x5e, 0x43, 0xda, 0xa8, 0xab, 0x18,
	0xe5, 0xd5, 0x69, 0x29, 0xa0, 0xdc, 0x0f, 0xb3, 0xfd, 0x0f, 0xe6, 0x05, 0x4e, 0xf4, 0x71, 0xe8,
	0x7c, 0x1b, 0x64, 0x12, 0x6b, 0xad, 0x6b, 0xf4, 0x1a, 0xaf, 0x60, 0x42, 0xcc, 0x9e, 0xc3, 0x6c,
	0x5c, 0x1c, 0x2e, 0xf2, 0x6a, 0xaa, 0xbe, 0x4f, 0x5b, 0x68, 0xb5, 0x67, 0x1e, 0x20, 0x11, 0x80,
	0x08, 0x47, 0xb5, 0xdf, 0xec, 0x6c, 0x12, 0x2b, 0x35, 0x16, 0x90, 0x6f, 0x28, 0xd4, 0xec, 0xba,
	0xe8, 0x7c, 0xab, 0x59, 0x86, 0xa8, 0x5a, 0x6a, 0x9c, 0x57, 0xe2, 0x1f, 0x57, 0x13, 0xde, 0x41,
	0x22, 0x1a, 0xcf, 0x86, 0x29, 0x34, 0xec, 0xfc, 0xfc, 0x3f, 0xdc, 0x2d, 0x6a, 0x0e, 0x1e, 0xb3,
	0xb7, 0x63, 0x3d, 0xf9, 0x7a, 0x22, 0x37, 0xbf, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x55, 0x26,
	0xfe, 0x9c, 0x92, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for GreetService service

type GreetServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...client.CallOption) (*GreetResponse, error)
}

type greetServiceClient struct {
	c           client.Client
	serviceName string
}

func NewGreetServiceClient(serviceName string, c client.Client) GreetServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "greet"
	}
	return &greetServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...client.CallOption) (*GreetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "GreetService.Greet", in)
	out := new(GreetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreetService service

type GreetServiceHandler interface {
	Greet(context.Context, *GreetRequest, *GreetResponse) error
}

func RegisterGreetServiceHandler(s server.Server, hdlr GreetServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&GreetService{hdlr}, opts...))
}

type GreetService struct {
	GreetServiceHandler
}

func (h *GreetService) Greet(ctx context.Context, in *GreetRequest, out *GreetResponse) error {
	return h.GreetServiceHandler.Greet(ctx, in, out)
}
